using ApiPokemonCSharp.Data;
using ApiPokemonCSharp.Models;
using ApiPokemonCSharp.Repositorios.Repositorios;
using Microsoft.EntityFrameworkCore;

namespace ApiPokemonCSharp.Repositorios;

public class PokeMoveRepository : IPokeMoveRepository
{

    private readonly PokemonDbContext _dbContext;

    public PokeMoveRepository(PokemonDbContext sistemaTarefasDbContext)
    {
        _dbContext = sistemaTarefasDbContext;
    }

    public async Task<PokeMove> AddItem(PokeMove TVmEntity)
    {
        await _dbContext.Moves.AddAsync(TVmEntity);
        await _dbContext.SaveChangesAsync();

        return TVmEntity;
    }

    public async Task<bool> RemoveItem(int id)
    {
        PokeMove PokeMoveId = await SearchForId(id);

        if (PokeMoveId != null)
        {
            throw new Exception($"Move for Id: {id} was not found");
        }

        _dbContext.Moves.Remove(PokeMoveId);
        await _dbContext.SaveChangesAsync();
        return true;
    }

    public async Task<PokeMove> UpdateItem(PokeMove TVmEntity, int id)
    {
        PokeMove PokeMoveId = await SearchForId(id);

        if (PokeMoveId == null)
        {
            throw new Exception($"Move for Id: {id} was not found");
        }

        PokeMoveId.Name = TVmEntity.Name;
        PokeMoveId.Deleted = TVmEntity.Deleted;
        PokeMoveId.DeletedWhen = TVmEntity.DeletedWhen;
        PokeMoveId.Id = TVmEntity.Id;
        PokeMoveId.AttributeBuff = TVmEntity.AttributeBuff;
        PokeMoveId.AutoGeneratedCondition = TVmEntity.AutoGeneratedCondition;
        PokeMoveId.AutoGeneratedConditionChance = TVmEntity.AutoGeneratedConditionChance;
        PokeMoveId.GeneratedCondition = TVmEntity.GeneratedCondition;
        PokeMoveId.ConditionChance = TVmEntity.ConditionChance;
        PokeMoveId.Damage = TVmEntity.Damage;
        PokeMoveId.PercentageBuff = TVmEntity.PercentageBuff;
        PokeMoveId.PokeType = TVmEntity.PokeType;
        PokeMoveId.PokeTypeId = TVmEntity.PokeTypeId;
        PokeMoveId.Velocity = TVmEntity.Velocity;
        PokeMoveId.PokePokemonMoveList = TVmEntity.PokePokemonMoveList;

        _dbContext.Moves.Update(PokeMoveId);
        await _dbContext.SaveChangesAsync();

        return PokeMoveId;
    }

    public async Task<PokeMove> SearchForId(int id)
    {
        return await _dbContext.Moves.FirstOrDefaultAsync(x => x.Id == id);
    }

    public async Task<List<PokeMove>> SearchAll()
    {
        return await _dbContext.Moves.ToListAsync();
    }

	public async Task<List<PokeMove>> ShowAllMoveByType(int type)
	{
		return await _dbContext.Moves
				.Where(x => x.PokeTypeId == type)
				.ToListAsync();
	}

	public async Task<List<PokeMove>> ShowAllMoveByPokemon(int pokemon)
	{
		return await _dbContext.Moves
				.Include(a => a.PokePokemonMoveList)
			    .Where(x => x.PokePokemonMoveList.Any(z => z.PokePokemonId == pokemon))
				.ToListAsync();
	}
}
