using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApiPokemonCSharp.Migrations
{
    /// <inheritdoc />
    public partial class InitialDb : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Items",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Price = table.Column<int>(type: "int", nullable: false),
                    AttributeBuff = table.Column<int>(type: "int", nullable: false),
                    IncreaseBuff = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    Deleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedWhen = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Items", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Types",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    PokemonType = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    Deleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedWhen = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Types", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Effectiveness",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Multiplier = table.Column<int>(type: "int", nullable: false),
                    PokeTypeId = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    Deleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedWhen = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Effectiveness", x => x.Id);
                    table.ForeignKey(
                        name: "fk_poke_type_x_poke_effective",
                        column: x => x.PokeTypeId,
                        principalTable: "Types",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Moves",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Damage = table.Column<int>(type: "int", nullable: false),
                    Velocity = table.Column<int>(type: "int", nullable: false),
                    ConditionChance = table.Column<int>(type: "int", nullable: false),
                    GeneratedCondition = table.Column<int>(type: "int", nullable: false),
                    AutoGeneratedConditionChance = table.Column<int>(type: "int", nullable: false),
                    AutoGeneratedCondition = table.Column<int>(type: "int", nullable: false),
                    PercentageBuff = table.Column<int>(type: "int", nullable: false),
                    AttributeBuff = table.Column<int>(type: "int", nullable: false),
                    PokeTypeId = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    Deleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedWhen = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Moves", x => x.Id);
                    table.ForeignKey(
                        name: "fk_poke_type_x_poke_move",
                        column: x => x.PokeTypeId,
                        principalTable: "Types",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Pokemons",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    HpPokemon = table.Column<int>(type: "int", nullable: false),
                    AttackPokemon = table.Column<int>(type: "int", nullable: false),
                    DefensePokemon = table.Column<int>(type: "int", nullable: false),
                    SpeedPokemon = table.Column<int>(type: "int", nullable: false),
                    SpecialAttackPokemon = table.Column<int>(type: "int", nullable: false),
                    SpecialDefensePokemon = table.Column<int>(type: "int", nullable: false),
                    PokeItemId = table.Column<int>(type: "int", nullable: false),
                    PokePrimaryTypeId = table.Column<int>(type: "int", nullable: false),
                    PokeSecondaryTypeId = table.Column<int>(type: "int", nullable: true),
                    Name = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    Deleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedWhen = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Pokemons", x => x.Id);
                    table.ForeignKey(
                        name: "fk_poke_item_x_poke_pokemon",
                        column: x => x.PokeItemId,
                        principalTable: "Items",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_poke_primary_type_x_poke_pokemon",
                        column: x => x.PokePrimaryTypeId,
                        principalTable: "Types",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_poke_secondary_type_x_poke_pokemon",
                        column: x => x.PokeSecondaryTypeId,
                        principalTable: "Types",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Weakness",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Multiplier = table.Column<int>(type: "int", nullable: false),
                    PokeTypeId = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    Deleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedWhen = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Weakness", x => x.Id);
                    table.ForeignKey(
                        name: "fk_poke_type_x_poke_weakness",
                        column: x => x.PokeTypeId,
                        principalTable: "Types",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "PokemonMove",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    PokePokemonId = table.Column<int>(type: "int", nullable: false),
                    PokeMoveId = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    Deleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedWhen = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PokemonMove", x => x.Id);
                    table.ForeignKey(
                        name: "fk_poke_move_x_poke_pokemon_move",
                        column: x => x.PokeMoveId,
                        principalTable: "Moves",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_poke_pokemon_x_poke_pokemon_move",
                        column: x => x.PokePokemonId,
                        principalTable: "Pokemons",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "idx_fk_poke_type_x_poke_effective",
                table: "Effectiveness",
                column: "PokeTypeId");

            migrationBuilder.CreateIndex(
                name: "idx_fk_poke_type_x_poke_move",
                table: "Moves",
                column: "PokeTypeId");

            migrationBuilder.CreateIndex(
                name: "idx_fk_poke_move_x_poke_pokemon_move",
                table: "PokemonMove",
                column: "PokeMoveId");

            migrationBuilder.CreateIndex(
                name: "idx_fk_poke_pokemon_x_poke_pokemon_move",
                table: "PokemonMove",
                column: "PokePokemonId");

            migrationBuilder.CreateIndex(
                name: "idx_fk_poke_item_x_poke_pokemon",
                table: "Pokemons",
                column: "PokeItemId");

            migrationBuilder.CreateIndex(
                name: "idx_fk_poke_primary_type_x_poke_pokemon",
                table: "Pokemons",
                column: "PokePrimaryTypeId");

            migrationBuilder.CreateIndex(
                name: "idx_fk_poke_secondary_type_x_poke_pokemon",
                table: "Pokemons",
                column: "PokeSecondaryTypeId");

            migrationBuilder.CreateIndex(
                name: "idx_fk_poke_type_x_poke_weakness",
                table: "Weakness",
                column: "PokeTypeId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Effectiveness");

            migrationBuilder.DropTable(
                name: "PokemonMove");

            migrationBuilder.DropTable(
                name: "Weakness");

            migrationBuilder.DropTable(
                name: "Moves");

            migrationBuilder.DropTable(
                name: "Pokemons");

            migrationBuilder.DropTable(
                name: "Items");

            migrationBuilder.DropTable(
                name: "Types");
        }
    }
}
