
using static ApiPokemonCSharp.Enums.GlobalTypes;

namespace ApiPokemonCSharp.Models;

public class PokeMove : BaseModel
{
    public int Damage { get; set; }

    public int Velocity { get; set; }

    public int ConditionChance { get; set; }

    public PokemonStatus GeneratedCondition { get; set; }

    public int AutoGeneratedConditionChance { get; set; }

    public PokemonStatus AutoGeneratedCondition { get; set; }

    public int PercentageBuff {  get; set; }

    public PokemonAttribute AttributeBuff { get; set; }

    public int PokeTypeId { get; set; }

    public virtual PokeType? PokeType { get; set; }

    public List<PokePokemonMove>? PokePokemonMoveList { get; set; }
}

