
using static ApiPokemonCSharp.Enums.TiposGlobais;

namespace ApiPokemonCSharp.Models;

public class PokeMove : BaseModel
{
    public int Damage { get; set; }

    public int Velocity { get; set; }

    public int ConditionChance { get; set; }

    public PokemonStatus GeneratedCondition { get; set; }

    public int AutoGeneratedConditionChance { get; set; }

    public PokemonStatus AutoGeneratedCondition { get; set; }

    public PokemonType MovementType { get; set; }

    public int PercentageBuff {  get; set; }

    public PokemonAttribute AttributeBuff { get; set; }

}

